version: '3.3'

services:
  blog:
    image: yet-another-blog/application
    user: ${UID:?UID is not set}:${GID:?GID is not set}
    build:
      context: ./app/
      args:
        - FLAG=${FLAG:?FLAG is not set}
        - HOST=${HOST:?HOST is not set}
        - FQDN=${FQDN:?FQDN is not set}
    networks:
      - internal
    ports:
      - 5000
    env_file: .env
    volumes:
      - ./certs/certbot/letsencrypt:/etc/letsencrypt:ro

  proxy:
    image: reverse-proxy
    build:
      context: ./proxy/
      dockerfile: Dockerfile
      args:
        # Just HTTPS stuff :)
        - FQDN=${FQDN:?FQDN is not set}
    restart: on-failure
    volumes:
      - ./certs/certbot/letsencrypt:/etc/letsencrypt
      - ./certs/certbot/www:/var/www/certbot

    networks:
      - external
      - internal
    ports:
      - 80:80
      - 443:443

networks:
  external:
  internal:
