version: '3.3'

services:
  blog:
    image: yet-another-blog/application
    build:
      context: ./app/
      args:
        - FLAG=${FLAG:?FLAG is not set}
        - HOST_IP=${HOST_IP:?HOST_IP is not set}
    networks:
      - internal
    ports:
      - 5000
    env_file: .env
    volumes:
      - certs:/certs:ro

  proxy:
    image: reverse-proxy
    build:
      context: ./proxy/
      dockerfile: Dockerfile
      args:
        # Just HTTPS stuff :)
        - FQDN=${FQDN:?FQDN is not set}
    restart: on-failure
    volumes:
      - certs/:/etc/nginx/ssl
      - ./proxy/https.conf:/etc/nginx/conf.d/https.conf

    networks:
      - external
      - internal
    ports:
      - 80:80

volumes:
  certs:
    driver: local

networks:
  external:
  internal:
