FROM python:3.9-slim

COPY requirements.txt /app/requirements.txt
WORKDIR /app
RUN pip install -r requirements.txt

ENV FLAG=DCTF{cR0sS_s1t3_5cr1pt1nG_m4St3R}

COPY . /app

RUN chown -R 1337:1337 /app

CMD [ "waitress-serve", "--port=8000", "--call", "src:create_app"]
