{
 "title": "K8S",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Inflight requests",
   "type": "stat",
   "gridPos": { "h": 14, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000
      ],
      "dimensionFilters": [],
      "metricName": "apiserver_current_inflight_requests",
      "metricNamespace": "microsoft.containerservice/managedclusters",
      "region": "westeurope",
      "resources": [
       {
        "metricNamespace": "microsoft.containerservice/managedClusters",
        "region": "westeurope",
        "resourceGroup": "dctf23-challs",
        "resourceName": "dctf",
        "subscription": "735ebbdd-cfc9-4d04-8920-c6e061271654"
       }
      ],
      "timeGrain": "PT1M"
     },
     "subscription": "735ebbdd-cfc9-4d04-8920-c6e061271654"
    }
   ]
  },
  {
   "title": "Pod states",
   "type": "stat",
   "gridPos": { "h": 14, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "alias": "{{phase}}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000
      ],
      "dimensionFilters": [
       { "dimension": "namespace", "filters": [ "default" ], "operator": "eq" },
       {
        "dimension": "phase",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "kube_pod_status_phase",
      "metricNamespace": "microsoft.containerservice/managedclusters",
      "region": "westeurope",
      "resources": [
       {
        "metricNamespace": "microsoft.containerservice/managedClusters",
        "region": "westeurope",
        "resourceGroup": "dctf23-challs",
        "resourceName": "dctf",
        "subscription": "735ebbdd-cfc9-4d04-8920-c6e061271654"
       }
      ],
      "timeGrain": "PT1M",
      "top": ""
     },
     "subscription": "735ebbdd-cfc9-4d04-8920-c6e061271654"
    }
   ]
  },
  {
   "title": "PWN IP Throughput",
   "type": "stat",
   "gridPos": { "h": 14, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "alias": "{{direction}}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [
       {
        "dimension": "Direction",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "ByteCount",
      "metricNamespace": "microsoft.network/publicipaddresses",
      "region": "westeurope",
      "resources": [
       {
        "metricNamespace": "Microsoft.Network/publicIPAddresses",
        "region": "westeurope",
        "resourceGroup": "MC_DCTF23-Challs_dctf_westeurope",
        "resourceName": "challs_pwn_public_ip",
        "subscription": "735ebbdd-cfc9-4d04-8920-c6e061271654"
       }
      ],
      "timeGrain": "PT1M"
     },
     "subscription": "735ebbdd-cfc9-4d04-8920-c6e061271654"
    }
   ]
  },
  {
   "title": "Web IP Throughput",
   "type": "stat",
   "gridPos": { "h": 14, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Total",
      "alias": "{{direction}}",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [
       {
        "dimension": "Direction",
        "filters": [],
        "operator": "eq"
       }
      ],
      "metricName": "ByteCount",
      "metricNamespace": "microsoft.network/publicipaddresses",
      "region": "westeurope",
      "resources": [
       {
        "metricNamespace": "Microsoft.Network/publicIPAddresses",
        "region": "westeurope",
        "resourceGroup": "mc_dctf23-challs_dctf_westeurope",
        "resourceName": "kubernetes-a0fbbeb80be0645649282fc9c20fa287",
        "subscription": "735ebbdd-cfc9-4d04-8920-c6e061271654"
       }
      ],
      "timeGrain": "auto"
     },
     "subscription": "735ebbdd-cfc9-4d04-8920-c6e061271654"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "alias": "",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000
      ],
      "customNamespace": "microsoft.containerservice/managedclusters",
      "dimensionFilters": [],
      "metricName": "node_cpu_usage_percentage",
      "metricNamespace": "microsoft.containerservice/managedclusters",
      "region": "westeurope",
      "resources": [
       {
        "metricNamespace": "microsoft.containerservice/managedClusters",
        "region": "westeurope",
        "resourceGroup": "dctf23-challs",
        "resourceName": "dctf",
        "subscription": "735ebbdd-cfc9-4d04-8920-c6e061271654"
       }
      ],
      "timeGrain": "PT1M",
      "top": ""
     },
     "azureResourceGraph": { "query": "" },
     "subscription": "735ebbdd-cfc9-4d04-8920-c6e061271654",
     "subscriptions": [
      "735ebbdd-cfc9-4d04-8920-c6e061271654"
     ]
    }
   ]
  },
  {
   "title": "Network usage",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000
      ],
      "dimensionFilters": [],
      "metricName": "node_network_in_bytes",
      "metricNamespace": "microsoft.containerservice/managedclusters",
      "region": "westeurope",
      "resources": [
       {
        "metricNamespace": "microsoft.containerservice/managedClusters",
        "region": "westeurope",
        "resourceGroup": "dctf23-challs",
        "resourceName": "dctf",
        "subscription": "735ebbdd-cfc9-4d04-8920-c6e061271654"
       }
      ],
      "timeGrain": "PT1M"
     },
     "subscription": "735ebbdd-cfc9-4d04-8920-c6e061271654"
    },
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000
      ],
      "dimensionFilters": [],
      "metricName": "node_network_out_bytes",
      "metricNamespace": "microsoft.containerservice/managedclusters",
      "region": "westeurope",
      "resources": [
       {
        "metricNamespace": "microsoft.containerservice/managedClusters",
        "region": "westeurope",
        "resourceGroup": "dctf23-challs",
        "resourceName": "dctf",
        "subscription": "735ebbdd-cfc9-4d04-8920-c6e061271654"
       }
      ],
      "timeGrain": "PT1M"
     },
     "subscription": "735ebbdd-cfc9-4d04-8920-c6e061271654"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000
      ],
      "dimensionFilters": [],
      "metricName": "node_memory_working_set_percentage",
      "metricNamespace": "microsoft.containerservice/managedclusters",
      "region": "westeurope",
      "resources": [
       {
        "metricNamespace": "microsoft.containerservice/managedClusters",
        "region": "westeurope",
        "resourceGroup": "dctf23-challs",
        "resourceName": "dctf",
        "subscription": "735ebbdd-cfc9-4d04-8920-c6e061271654"
       }
      ],
      "timeGrain": "PT1M"
     },
     "subscription": "735ebbdd-cfc9-4d04-8920-c6e061271654"
    }
   ]
  },
  {
   "title": "Disk usage",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {
     "azureMonitor": {
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000
      ],
      "dimensionFilters": [],
      "metricName": "node_disk_usage_percentage",
      "metricNamespace": "microsoft.containerservice/managedclusters",
      "region": "westeurope",
      "resources": [
       {
        "metricNamespace": "microsoft.containerservice/managedClusters",
        "region": "westeurope",
        "resourceGroup": "dctf23-challs",
        "resourceName": "dctf",
        "subscription": "735ebbdd-cfc9-4d04-8920-c6e061271654"
       }
      ],
      "timeGrain": "PT1M"
     },
     "subscription": "735ebbdd-cfc9-4d04-8920-c6e061271654"
    }
   ]
  }
 ]
}