{
 "title": "CTFd flask",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "CTFD", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "HTTP requests per minute",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 20, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(flask_http_request_total[1m])) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Number of errors per minute",
   "type": "stat",
   "gridPos": { "h": 10, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(flask_http_request_exceptions_total{job=\"dctf_ctfd_flask\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latencies by status",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(flask_http_request_duration_seconds_sum{instance=\"dctf.si:80\"}[1m])) by (status) / sum(rate(flask_http_request_duration_seconds_count{instance=\"dctf.si:80\"}[1m])) by (status)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}